### ISSUE TITLE
Все числа вынести в переменные с говорящим названием

### ISSUE THREAD

**Issue by coursar** [ramilya-k/Sportmaster#2]
https://github.com/ramilya-k/Sportmaster/blob/f5829c35a782de732c1a23a3785453663e641e1c/src/Main.java#L5-L28

**Comment by ramilya-k** [comment]
fixes #2

**Comment by coursar** [comment]
Это надо писать в комментарии коммита, а не здесь

**Comment by coursar** [comment]
Числа 15_000, 1_000, 70 и т.д. нужно вынести в переменные с говорящими именами.

**Comment by ramilya-k** [comment]
``Не понимаю о каких именно переменных идет речь. 1_000 и 70 я в последнем комите исправляла проблему с именами, в отдельные переменные они вынесены, укажите какие именно строки в коде вызывают вопрос. Код выше изначальный, далее уже были исправления, я добавляла их в комите, просто не знаю как приложить тут

**Comment by coursar** [comment]
Например, `if (totalPurchases <= 15_000) {`, 15_000 нужно выносить в переменную и другие подобные числа тоже.
